// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGCo6B60XEW-_rnwmIrP0LUWWvxADions',
    appId: '1:1090938428047:web:b08d9ff431c98a64892efa',
    messagingSenderId: '1090938428047',
    projectId: 'portfolio-efada',
    authDomain: 'portfolio-efada.firebaseapp.com',
    storageBucket: 'portfolio-efada.firebasestorage.app',
    measurementId: 'G-R7VTR0CRV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiLtNemg038EjECucn9G4pqJ3WQPfJjA0',
    appId: '1:1090938428047:android:01a54c50950117de892efa',
    messagingSenderId: '1090938428047',
    projectId: 'portfolio-efada',
    storageBucket: 'portfolio-efada.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK7LNdeLHKfNuefOJduUEYuN_2cW3xfy0',
    appId: '1:1090938428047:ios:ff99528b7dbe0deb892efa',
    messagingSenderId: '1090938428047',
    projectId: 'portfolio-efada',
    storageBucket: 'portfolio-efada.firebasestorage.app',
    iosBundleId: 'com.example.aaliyaPortfolioApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK7LNdeLHKfNuefOJduUEYuN_2cW3xfy0',
    appId: '1:1090938428047:ios:ff99528b7dbe0deb892efa',
    messagingSenderId: '1090938428047',
    projectId: 'portfolio-efada',
    storageBucket: 'portfolio-efada.firebasestorage.app',
    iosBundleId: 'com.example.aaliyaPortfolioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGCo6B60XEW-_rnwmIrP0LUWWvxADions',
    appId: '1:1090938428047:web:63ee42398ecceb1b892efa',
    messagingSenderId: '1090938428047',
    projectId: 'portfolio-efada',
    authDomain: 'portfolio-efada.firebaseapp.com',
    storageBucket: 'portfolio-efada.firebasestorage.app',
    measurementId: 'G-SRL58MC9X6',
  );
}
